[workspace]
authors = ["carlstadie <116877335+carlstadie@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "LidarProcessing"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
LidarProcessing = 'python ./tui.py'

[dependencies]
pdal = ">=2.8.4,<3"
laspy = ">=2.6.1,<3"
shapely = ">=2.1.2,<3"
geopandas = ">=1.1.1,<2"
rasterio = ">=1.4.3,<2"
numpy = ">=2.3.4,<3"
scipy = ">=1.16.3,<2"
tqdm = ">=4.67.1,<5"
textual = ">=6.5.0,<7"
python = ">=3.13.9,<3.14"
gdal = ">=3.10.3,<4"
psutil = ">=7.1.3,<8"
